# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ChuckNorrisApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorrisApp
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 6.0'

end
